# Generated by Django 5.1.7 on 2025-03-22 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("se7ati_app", "0003_ville"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quartier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_quartier",
                    models.CharField(max_length=100, verbose_name="Nom du quartier"),
                ),
                (
                    "ville",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quartiers",
                        to="se7ati_app.ville",
                        verbose_name="Ville",
                    ),
                ),
            ],
        ),
    ]
