# Generated by Django 5.1.7 on 2025-03-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("se7ati_app", "0004_quartier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="medical_history",
        ),
        migrations.AddField(
            model_name="patient",
            name="date_naissance",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="genre",
            field=models.CharField(
                choices=[("homme", "Homme"), ("femme", "Femme"), ("autre", "Autre")],
                default="autre",
                max_length=10,
                verbose_name="Genre",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="poids",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Poids (en kg)"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="taille",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Taille (en cm)"
            ),
        ),
    ]
