# Generated by Django 5.1.7 on 2025-03-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("se7ati_app", "0005_remove_patient_medical_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="genre",
            field=models.CharField(
                choices=[
                    ("homme", "Homme"),
                    ("femme", "Femme"),
                    ("non-specifie", "Non spécifié"),
                ],
                default="autre",
                max_length=30,
                verbose_name="Genre",
            ),
        ),
    ]
