# Generated by Django 5.1.7 on 2025-03-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("se7ati_app", "0005_user_stream_chat_token"),
        ("se7ati_app", "0006_alter_patient_genre"),
    ]

    operations = []
