# Generated by Django 5.1.7 on 2025-03-25 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("se7ati_app", "0007_merge_20250322_2225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="genre",
            field=models.CharField(
                choices=[
                    ("homme", "Homme"),
                    ("femme", "Femme"),
                    ("non-specifie", "Non spécifié"),
                ],
                max_length=30,
                verbose_name="Genre",
            ),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
