# Generated by Django 5.1.7 on 2025-04-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("se7ati_app", "0011_romm_message"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Romm",
            new_name="Room",
        ),
    ]
